# Generated by Django 2.2.1 on 2020-09-03 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceCheckTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('username', models.CharField(max_length=100, verbose_name='上传用户')),
                ('status', models.CharField(blank=True, choices=[('S', '通过'), ('F', '拒绝'), ('D', '待审核')], default='D', max_length=10, verbose_name='状态')),
                ('img', models.FileField(upload_to='static/upload_temp', verbose_name='上传文件')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='系统收录时间')),
            ],
            options={
                'verbose_name': '人脸审核管理',
                'verbose_name_plural': '人脸审核管理',
            },
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('as_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='别名')),
                ('status', models.CharField(blank=True, choices=[('E', '生效'), ('F', '失效')], default='E', max_length=10, verbose_name='状态')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='系统收录时间')),
            ],
            options={
                'verbose_name': '人脸库',
                'verbose_name_plural': '人脸库',
            },
        ),
        migrations.CreateModel(
            name='UploadFileTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='static/upload_temp', verbose_name='上传文件')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='系统收录时间')),
            ],
            options={
                'verbose_name': '临时上传文件',
                'verbose_name_plural': '临时上传文件',
            },
        ),
        migrations.CreateModel(
            name='FaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('folder', models.CharField(max_length=100, null=True, verbose_name='文件夹')),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='系统收录时间')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces_main', to='app.Faces', verbose_name='人物')),
            ],
            options={
                'verbose_name': '人脸详细信息',
                'verbose_name_plural': '人脸详细信息',
            },
        ),
    ]
